'use client';

import { RasterButton, RasterLink } from './raster-button';

import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { campaigns, campaignPosts, compact, count, csvFile, demoCreators, demoPosts, postEngagement, sections, totals, type DemoPost, type Metric, type Section } from '@/lib/dashboard-demo';
import { Banner, Choice, Dots, Icon, Menu, Modal, PlatformMark } from './ui';
import { PerformanceChart } from './chart';
import { CurrentButton } from './current-button';
import { CreatorTable } from './creator-table';

type View = { tab: Section; view: string; campaign: string; range: string; from: number; to: number; platform: string; metric: Metric; mode: string; query: string; sort: string; status: string; page: number };
const initial: View = { tab: 'overview', view: 'statistics', campaign: 'autumn', range: 'Lifetime', from: 1, to: 24, platform: 'All platforms', metric: 'views', mode: 'Daily', query: '', sort: 'Most views', status: 'All statuses', page: 1 };
const icons: Record<Section, string> = { overview: 'overview', creators: 'creators', posts: 'posts', feed: 'feed', plan: 'calendar', analytics: 'analytics', team: 'team' };
function readView(): View {
  const q = new URLSearchParams(location.search);
  const v = { ...initial };
  if (sections.some(s => s.id === q.get('tab'))) v.tab = q.get('tab') as Section;
  if (campaigns.some(c => c.id === q.get('campaign'))) v.campaign = q.get('campaign')!;
  if (['statistics', 'top-posts', 'calendar'].includes(q.get('view') ?? '')) v.view = q.get('view')!;
  if (['views', 'posts', 'engagement'].includes(q.get('metric') ?? '')) v.metric = q.get('metric') as Metric;
  if (q.get('mode') === 'Cumulative') v.mode = 'Cumulative';
  if (['Lifetime', '6M', '1M', '14D', '7D', 'Custom'].includes(q.get('range') ?? '')) v.range = q.get('range')!;
  if (['All platforms', 'TikTok', 'Instagram'].includes(q.get('platform') ?? '')) v.platform = q.get('platform')!;
  v.from = Math.max(1, Math.min(24, Math.floor(Number(q.get('from'))) || 1)); v.to = Math.max(v.from, Math.min(24, Math.floor(Number(q.get('to'))) || 24));
  v.page = Math.max(1, Math.min(21, Math.floor(Number(q.get('page'))) || 1));
  v.query = (q.get('query') ?? '').slice(0, 120);
  if (['Most views', 'Most recent', 'Most engagement', 'Creator A–Z'].includes(q.get('sort') ?? '')) v.sort = q.get('sort')!;
  if (['All statuses', 'Active', 'Inactive', 'Live', 'Deleted', 'Publishing', 'In review'].includes(q.get('status') ?? '')) v.status = q.get('status')!;
  return v;
}

export function DashboardWorkspace() {
  const [state, setState] = useState<View>(initial), [open, setOpen] = useState<string | null>(null), [mobile, setMobile] = useState(false);
  const [dialog, setDialog] = useState<string | null>(null), [selectedPost, setSelectedPost] = useState<DemoPost | null>(null), [selectedCreator, setSelectedCreator] = useState<number | null>(null);
  const [selected, setSelected] = useState<string[]>([]), [flagged, setFlagged] = useState<string[]>([]), [toast, setToast] = useState('');
  const [planFilter, setPlanFilter] = useState('Active'), [planFlagged, setPlanFlagged] = useState<string[]>([]);
  const [members, setMembers] = useState([{ name: 'Alex Carter', email: 'alex@meridian.example', role: 'Admin' }, { name: 'Jamie Chen', email: 'jamie@meridian.example', role: 'Member' }, { name: 'Sam Rivera', email: 'sam@meridian.example', role: 'Member' }]);
  const [profile, setProfile] = useState('Alex Carter'), [notificationsRead, setNotificationsRead] = useState(false);
  const [emailDigest, setEmailDigest] = useState(true), [reduced, setReduced] = useState(false);
  const closeMenu = useCallback((v: string | null) => setOpen(v), []);
  useEffect(() => {
    setState(readView());
    const linkedPost = campaignPosts(readView().campaign).find(p => p.id === new URLSearchParams(location.search).get('post'));
    if (linkedPost) { setSelectedPost(linkedPost); setDialog('post'); }
    const back = () => { setState(readView()); setSelected([]); setOpen(null); setMobile(false); };
    window.addEventListener('popstate', back);
    return () => window.removeEventListener('popstate', back);
  }, []);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(''), 4500); return () => clearTimeout(t); }, [toast]);
  useEffect(() => { if (!mobile) return; const key = (e: KeyboardEvent) => { if (e.key === 'Escape') setMobile(false); }; document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key); }, [mobile]);
  useEffect(() => {
    const media = window.matchMedia('(min-width: 851px)');
    const close = () => { if (media.matches) setMobile(false); };
    media.addEventListener('change', close);
    return () => media.removeEventListener('change', close);
  }, []);
  function update(patch: Partial<View>, replace = false) {
    const next = { ...state, ...patch };
    setState(next); setOpen(null); setSelected([]);
    const params = new URLSearchParams();
    Object.entries(next).forEach(([k, v]) => { if (v !== initial[k as keyof View]) params.set(k, String(v)); });
    const url = `${location.pathname}${params.size ? `?${params}` : ''}`;
    if (replace) history.replaceState(null, '', url); else history.pushState(null, '', url);
  }
  function navigate(tab: Section) { update({ tab, query: '', status: 'All statuses', page: 1 }); setMobile(false); }
  function range(value: string) { update({ range: value, from: value === '7D' ? 18 : value === '14D' ? 11 : 1, to: 24, page: 1 }); }
  const campaign = campaigns.find(c => c.id === state.campaign)!;
  const allPosts = useMemo(() => campaignPosts(state.campaign), [state.campaign]);
  const periodPosts = useMemo(() => allPosts.filter(p => p.day >= state.from && p.day <= state.to && (state.platform === 'All platforms' || p.platform === state.platform)), [allPosts, state.from, state.to, state.platform]);
  const total = totals(periodPosts), entire = totals(allPosts);
  const sorted = useMemo(() => periodPosts.filter(p => `${demoCreators[p.creator].name} ${demoCreators[p.creator].handle} ${p.title} ${p.id}`.toLowerCase().includes(state.query.toLowerCase()) && (state.status === 'All statuses' || p.status === state.status || demoCreators[p.creator].status === state.status)).sort((a, b) => state.sort === 'Most recent' ? b.day - a.day : state.sort === 'Most engagement' ? postEngagement(b) - postEngagement(a) : state.sort === 'Creator A–Z' ? demoCreators[a.creator].name.localeCompare(demoCreators[b.creator].name) : b.views - a.views), [periodPosts, state.query, state.sort, state.status]);
  const topPosts = [...periodPosts].sort((a, b) => b.views - a.views).slice(0, 8);
  const roster = demoCreators.filter(c => allPosts.some(p => p.creator === c.id));
  const activeInfo = sections.find(s => s.id === state.tab)!;
  const menuProps = { open, setOpen: closeMenu };
  const exportData = (rows = sorted) => { csvFile(rows); setOpen(null); setToast(`Exported ${rows.length} demo posts.`); };
  const filteredTotal = sorted.length, perPage = state.tab === 'feed' || state.view === 'top-posts' ? 12 : 16;
  const pages = Math.max(1, Math.ceil(filteredTotal / perPage)), page = Math.min(state.page, pages), pagePosts = sorted.slice((page - 1) * perPage, page * perPage);
  const selectedRows = sorted.filter(p => selected.includes(p.id));
  const viewPost = (p: DemoPost) => { setSelectedPost(p); setDialog('post'); };
  const chartPanel = <section className="ds-blue-panel" aria-label="Performance graph"><header className="ds-chart-header"><div className="ds-chart-tabs" role="group" aria-label="Chart metric">{(['views', 'posts', 'engagement'] as Metric[]).map(metric => <RasterButton key={metric} aria-pressed={state.metric === metric} onClick={() => update({ metric })}>{metric === 'views' ? 'Views' : metric === 'posts' ? 'Posts' : 'Engagement'}</RasterButton>)}</div><div className="ds-chart-controls"><Menu id="chart-mode" label={state.mode} {...menuProps}>{['Daily', 'Cumulative'].map(mode => <Choice key={mode} active={state.mode === mode} onClick={() => update({ mode })}>{mode}</Choice>)}</Menu><Menu id="chart-platform" label={state.platform} {...menuProps}>{['All platforms', 'TikTok', 'Instagram'].map(platform => <Choice key={platform} active={state.platform === platform} onClick={() => update({ platform, page: 1 })}>{platform}</Choice>)}</Menu></div></header><p className="ds-chart-title">{state.metric === 'views' ? 'Views' : state.metric === 'posts' ? 'Posts' : 'Interactions'} over time <span>{state.mode.toLowerCase()}</span></p><PerformanceChart posts={periodPosts} from={state.from} to={state.to} metric={state.metric} cumulative={state.mode === 'Cumulative'} /><div className="ds-chart-legend">{(['TikTok', 'Instagram'] as const).map(platform => <RasterButton key={platform} aria-pressed={state.platform === platform} onClick={() => update({ platform: state.platform === platform ? 'All platforms' : platform, page: 1 })}><PlatformMark name={platform} /><strong>{total.views ? (totals(periodPosts.filter(p => p.platform === platform)).views / total.views * 100).toFixed(1) : '0'}%</strong><span>{platform}</span></RasterButton>)}<span>Share of views</span></div></section>;

  function renderToolbar({ creators = false }: { creators?: boolean }) { return <div className="ds-list-toolbar"><label className="ds-search"><Icon name="search" /><input aria-label={creators ? 'Search creators' : 'Search posts'} type="search" placeholder={creators ? 'Find a creator…' : 'Search content, creator, or post ID…'} value={state.query} onChange={e => update({ query: e.target.value, page: 1 }, true)} /></label><div><Menu id="list-status" label={state.status} {...menuProps}>{(creators ? ['All statuses', 'Active', 'Inactive'] : ['All statuses', 'Live', 'Deleted']).map(status => <Choice key={status} active={state.status === status} onClick={() => update({ status, page: 1 })}>{status}</Choice>)}</Menu>{!creators && <><Menu id="list-platform" label={state.platform} {...menuProps}>{['All platforms', 'TikTok', 'Instagram'].map(platform => <Choice key={platform} active={state.platform === platform} onClick={() => update({ platform, page: 1 })}>{platform}</Choice>)}</Menu><Menu id="list-sort" label={state.sort} {...menuProps}>{['Most views', 'Most recent', 'Most engagement', 'Creator A–Z'].map(sort => <Choice key={sort} active={state.sort === sort} onClick={() => update({ sort, page: 1 })}>{sort}</Choice>)}</Menu></>}</div></div>; }
  const pagination = <div className="ds-pagination"><span>{sorted.length ? `${(page - 1) * perPage + 1}–${Math.min(page * perPage, sorted.length)} of ${count(sorted.length)} posts` : 'No matching posts'}</span><div><RasterButton aria-label="Previous page" disabled={page === 1} onClick={() => update({ page: page - 1 })}><Icon name="chevron" /></RasterButton><span>{page} / {pages}</span><RasterButton aria-label="Next page" disabled={page === pages} onClick={() => update({ page: page + 1 })}><Icon name="chevron" /></RasterButton></div></div>;

  return <div className="ds-app" data-quiet={reduced}>
    <Banner />
    <RasterButton className="ds-mobile-toggle" aria-label={mobile ? 'Close navigation' : 'Open navigation'} aria-expanded={mobile} onClick={() => setMobile(!mobile)}><Icon name={mobile ? 'close' : 'menu'} /></RasterButton>
    {mobile && <RasterButton className="ds-mobile-backdrop" aria-label="Close navigation" onClick={() => setMobile(false)} />}
    <aside className="ds-sidebar" data-open={mobile} aria-label="Workspace sidebar"><RasterLink href="/" className="ds-logo" aria-label="8x Social landing page"><img src="/8x.svg" width="68" height="47" alt="8x" /><span>social</span><Dots /></RasterLink>
      <Menu id="workspace-picker" label="Switch workspace" align="left" {...menuProps} className="ds-workspace-picker" trigger={<><img className="ds-workspace-mark" src="/dashboard/meridian.svg" width="44" height="44" alt="" /><span><strong>Meridian</strong><small>Brand workspace</small></span><Icon name="chevron" size={15} /></>}><span className="ds-menu-caption">Your workspaces</span><Choice active onClick={() => setOpen(null)} description="2 campaigns · Demo workspace">Meridian</Choice><div className="ds-menu-note">This preview contains one illustrative brand workspace.</div></Menu>
      <Menu id="campaign-picker" label="Switch campaign" align="left" {...menuProps} className="ds-campaign-picker" trigger={<><span><strong>{campaign.name}</strong><span className="ds-campaign-track"><i /><small>24 / 30 days</small></span></span><Icon name="down" size={13} /></>}><span className="ds-menu-caption">Your campaigns</span>{campaigns.map(c => <Choice key={c.id} active={c.id === state.campaign} description={c.country} onClick={() => update({ ...initial, campaign: c.id })}>{c.name}</Choice>)}</Menu>
      <nav className="ds-navigation" aria-label="Dashboard sections">{sections.map(s => <RasterLink key={s.id} href={`?tab=${s.id}`} className={`ds-nav-item ${s.id === 'team' ? 'ds-nav-team' : ''}`} aria-current={state.tab === s.id ? 'page' : undefined} onClick={e => { e.preventDefault(); navigate(s.id); }}><Icon name={icons[s.id]} /><span>{s.label}</span>{state.tab === s.id ? <Dots /> : s.id === 'creators' ? <small>{entire.creators}</small> : s.id === 'posts' ? <small>{entire.posts}</small> : <Icon name="outward" size={14} />}<span className="ds-nav-hint">{s.description}</span></RasterLink>)}</nav>
      <div className="ds-sidebar-bottom"><RasterButton className="ds-manager" onClick={() => setDialog('message')}><img src="/media/showcase/28.jpg" width="39" height="39" alt="" /><span><strong>Maya Chen</strong><small>Account manager</small></span><span className="ds-send-well"><Icon name="send" size={17} /></span></RasterButton><RasterButton className="ds-profile" onClick={() => setDialog('profile')}><span className="ds-profile-portrait"><img src="/dashboard/alex-carter.webp" width="46" height="46" alt="" /></span><span><strong>{profile}</strong><small>View profile</small></span><Icon name="chevron" size={16} /></RasterButton><RasterButton className="ds-utility" onClick={() => setDialog('help')}><Icon name="help" />Help & support</RasterButton><RasterButton className="ds-utility" onClick={() => setDialog('settings')}><Icon name="settings" />Settings</RasterButton></div>
    </aside>
    <main id="main" className="ds-main">
      <header className="ds-main-header"><div><div className="ds-breadcrumb"><span>Meridian</span><span>/</span><span>{campaign.name}</span></div><h1>{state.tab === 'overview' ? 'Campaign overview' : activeInfo.label}</h1></div><div className="ds-header-actions"><RasterButton className="ds-demo-label" onClick={() => setDialog('about')}>Demo workspace</RasterButton><Menu id="notifications" label="Notifications" className="ds-notifications" {...menuProps} trigger={<><Icon name="bell" />{!notificationsRead && <i />}</>}><div className="ds-notification-heading"><strong>Activity</strong><RasterButton onClick={() => setNotificationsRead(true)}>{notificationsRead ? 'All read' : 'Mark all read'}</RasterButton></div>{[['Your September report is ready', 'Campaign reporting · 2 hours ago'], ['4 creators joined your network', 'Creator update · Yesterday'], ['Your content plan is shared', 'Autumn launch · 2 days ago']].map(([a, b], i) => <RasterButton className="ds-notification" key={a} onClick={() => { setNotificationsRead(true); if (i === 0) setDialog('export'); else navigate(i === 1 ? 'creators' : 'plan'); setOpen(null); }}><span className="ds-notification-dot" /><span><strong>{a}</strong><small>{b}</small></span></RasterButton>)}</Menu><CurrentButton className="ds-current-header" icon="download" onClick={() => setDialog('export')}>Export report</CurrentButton></div></header>
      <div className="ds-toolbar">{state.tab === 'overview' ? <div className="ds-view-switch" role="group" aria-label="Overview view">{[['statistics', 'Statistics', ''], ['top-posts', 'Top posts', 'analytics'], ['calendar', 'Pace & calendar', 'calendar']].map(([view, label, icon]) => <RasterButton key={view} aria-pressed={state.view === view} onClick={() => update({ view, page: 1 })}>{view === 'statistics' ? <Dots /> : <Icon name={icon} size={17} />}{label}</RasterButton>)}</div> : <p className="ds-section-description">{activeInfo.description}</p>}
        <div className="ds-date-controls"><Menu id="date-picker" label="Choose reporting dates" {...menuProps} trigger={<span><small>REPORTING PERIOD</small><strong>{String(state.from).padStart(2, '0')} — {state.to} Sep 2026 <Icon name="down" size={13} /></strong></span>}><DatePicker from={state.from} to={state.to} onApply={(from, to) => update({ from, to, range: 'Custom', page: 1 })} /></Menu><div className="ds-date-ruler" aria-hidden="true">{Array.from({ length: 24 }, (_, i) => <i key={i} data-active={i + 1 >= state.from && i + 1 <= state.to} />)}</div><Menu id="date-range" label={state.range} {...menuProps}>{['Lifetime', '6M', '1M', '14D', '7D'].map(r => <Choice key={r} active={state.range === r} onClick={() => range(r)} description={r === 'Lifetime' ? 'Since the campaign began' : undefined}>{r}</Choice>)}<Choice active={state.range === 'Custom'} onClick={() => setOpen('date-picker')}>Custom dates</Choice><div className="ds-menu-note">Demo campaign: 1–24 September 2026. Longer ranges include the full campaign.</div></Menu></div>
      </div>
      <div className="ds-route-content" key={`${state.tab}-${state.view}`}>
      {state.tab === 'overview' && state.view === 'statistics' && <><div className="ds-overview-grid"><section className="ds-performance"><header><h2>Performance</h2><Menu id="performance-options" label="Performance options" {...menuProps} trigger={<Icon name="more" size={18} />}><Choice onClick={() => setDialog('metrics')}>How metrics are calculated</Choice><Choice onClick={() => exportData(periodPosts)}>Export this period</Choice></Menu></header><div className="ds-main-metrics"><RasterButton onClick={() => update({ metric: 'views' })}><strong data-testid="total-views">{compact(total.views)}</strong><span>Views</span></RasterButton><RasterButton onClick={() => update({ metric: 'engagement' })}><strong>{total.views ? `${total.rate.toFixed(1)}%` : '—'}</strong><span>Engagement rate</span></RasterButton></div><div className="ds-metric-links">{[['posts', 'Published posts', total.posts, 'posts'], ['creators', 'Creators publishing', total.creators, 'creators'], ['heart', 'Total interactions', compact(total.engagement), 'analytics']].map(([icon, label, value, target]) => <RasterButton key={String(label)} onClick={() => navigate(target as Section)}><span className="ds-metric-icon"><Icon name={String(icon)} size={18} /></span><span>{label}</span><strong>{value}</strong><Icon name="outward" size={15} /></RasterButton>)}</div><div className="ds-small-metrics"><span>{compact(total.likes)} likes</span><b>·</b><span>{compact(total.comments)} comments</span><b>·</b><span>{compact(total.shares)} shares</span></div></section>{chartPanel}</div><section className="ds-post-shelf"><div className="ds-shelf-heading"><h2>Top-performing<br />posts</h2><p>By views · this period</p><RasterButton onClick={() => { navigate('posts'); }}><span><Icon name="arrow" /></span>View all {count(periodPosts.length)}</RasterButton><div className="ds-shelf-dots" /></div><div className="ds-shelf-cards">{topPosts.map(post => <PostCard key={post.id} post={post} onClick={() => viewPost(post)} />)}{!topPosts.length && <Empty onReset={() => update({ ...initial, campaign: state.campaign })} />}</div></section></>}
      {state.tab === 'overview' && state.view === 'calendar' && <Calendar posts={periodPosts} onDay={day => update({ tab: 'posts', from: day, to: day, range: 'Custom', page: 1 })} />}
      {((state.tab === 'overview' && state.view === 'top-posts') || state.tab === 'feed') && <section className="ds-content-panel">{renderToolbar({})}<div className="ds-feed-grid">{pagePosts.map(p => <PostCard key={p.id} post={p} onClick={() => viewPost(p)} />)}</div>{!pagePosts.length && <Empty onReset={() => update({ query: '', status: 'All statuses', platform: 'All platforms' })} />}{pagination}</section>}
      {state.tab === 'posts' && <section className="ds-content-panel">{renderToolbar({})}<div className="ds-table-scroll"><table className="ds-table"><thead><tr><th><input type="checkbox" aria-label={`Select all ${sorted.length} filtered posts`} checked={sorted.length > 0 && selected.length === sorted.length} onChange={e => setSelected(e.target.checked ? sorted.map(p => p.id) : [])} /></th><th>Content</th><th>Creator</th><th>Platform</th><th><RasterButton onClick={() => update({ sort: 'Most views' })}>Views <Icon name="down" size={12} /></RasterButton></th><th>Likes</th><th><RasterButton onClick={() => update({ sort: 'Most engagement' })}>Engagement</RasterButton></th><th><RasterButton onClick={() => update({ sort: 'Most recent' })}>Posted</RasterButton></th><th>Status</th></tr></thead><tbody>{pagePosts.map(p => <tr key={p.id} data-selected={selected.includes(p.id)}><td><input type="checkbox" aria-label={`Select ${p.id}`} checked={selected.includes(p.id)} onChange={e => setSelected(e.target.checked ? [...selected, p.id] : selected.filter(id => id !== p.id))} /></td><td><RasterButton className="ds-content-cell" onClick={() => viewPost(p)}><img src={p.poster} alt="" width="36" height="46" /><span><strong>{p.title}</strong><small>{p.id}{flagged.includes(p.id) ? ' · Flagged for review' : ''}</small></span><Icon name="play" size={14} /></RasterButton></td><td>{demoCreators[p.creator].handle}</td><td><PlatformMark name={p.platform} /></td><td><strong>{compact(p.views)}</strong></td><td>{compact(p.likes)}</td><td>{(postEngagement(p) / p.views * 100).toFixed(1)}%</td><td>{p.day} Sep</td><td><span className="ds-status">{p.status}</span></td></tr>)}</tbody></table></div>{!pagePosts.length && <Empty onReset={() => update({ query: '', status: 'All statuses', platform: 'All platforms' })} />}{pagination}</section>}
      {state.tab === 'creators' && <CreatorTable creators={roster} posts={periodPosts} query={state.query} status={state.status} page={state.page} context={`${state.campaign}-${state.from}-${state.to}-${state.platform}`} onQuery={query => update({ query, page: 1 }, true)} onStatus={status => update({ status, page: 1 })} onPage={page => update({ page })} onReset={() => update({ query: '', status: 'All statuses', page: 1 })} onView={id => { setSelectedCreator(id); setDialog('creator'); }} onPosts={handle => update({ tab: 'posts', query: handle, status: 'All statuses', page: 1 })} onVideo={viewPost} />}
      {state.tab === 'plan' && <section className="ds-content-panel"><div className="ds-plan-heading"><div><span className="ds-eyebrow">Shared direction</span><h2>Make it yours.</h2><p>A clear brief. Enough room for your own voice.</p></div><Menu id="plan-filter" label={planFilter} {...menuProps}>{['Active', 'Upcoming', 'Past', 'Flagged'].map(s => <Choice key={s} active={planFilter === s} onClick={() => { setPlanFilter(s); setOpen(null); }}>{s}</Choice>)}</Menu></div><div className="ds-plan-grid">{['The everyday edit', 'Show, don’t tell', 'A fresh perspective'].filter(t => planFilter !== 'Flagged' || planFlagged.includes(t)).map((title, i) => <article className="ds-plan-card" key={title}><div className="ds-plan-preview"><img src={demoPosts[i + 4].poster} alt="Creator video reference" /><RasterButton className="ds-play" aria-label={`Play reference for ${title}`} onClick={() => viewPost(demoPosts[i + 4])}><Icon name="play" /></RasterButton><span>FORMAT 0{i + 1}</span></div><div><small>{planFilter === 'Upcoming' ? '01–15 Oct' : planFilter === 'Past' ? '01–31 Aug' : '01–30 Sep'} · TikTok / Instagram</small><h3>{title}</h3><p>{['Bring the product into a routine your audience already knows. Start with a moment, not a sales pitch.', 'Let the result do the talking. Show one useful feature in a real setting, in your own words.', 'Share an honest observation. A relatable problem and a new way to solve it.'][i]}</p><RasterButton className="ds-text-button" onClick={() => { setPlanFlagged(planFlagged.includes(title) ? planFlagged.filter(t => t !== title) : [...planFlagged, title]); setToast(planFlagged.includes(title) ? 'Flag removed.' : 'Flagged for review in this demo.'); }}><Icon name="flag" size={16} />{planFlagged.includes(title) ? 'Flagged · undo' : 'Flag for review'}</RasterButton></div></article>)}</div>{planFilter === 'Flagged' && planFlagged.length === 0 && <p className="ds-empty">No formats flagged. Open an active format to flag it for review.</p>}<div className="ds-guidelines"><h3>Campaign guidelines</h3><p>Keep it honest. Show the product naturally. Include the required sponsorship disclosure. Use clear captions and original footage.</p><CurrentButton variant="secondary" icon="outward" onClick={() => setDialog('brief')}>Read the full brief</CurrentButton></div></section>}
      {state.tab === 'analytics' && <><div className="ds-analytics-heading"><span><strong>{compact(total.views)}</strong>Total campaign views</span><span><strong>{total.rate.toFixed(1)}%</strong>Engagement rate</span><span><strong>{count(total.posts)}</strong>Posts published</span></div>{chartPanel}<section className="ds-content-panel ds-analytics-sources"><h2>Platform performance</h2><div className="ds-platform-rows">{(['TikTok', 'Instagram'] as const).map(platform => { const t = totals(periodPosts.filter(p => p.platform === platform)); return <RasterButton key={platform} onClick={() => update({ tab: 'posts', platform, page: 1 })}><PlatformMark name={platform} /><strong>{platform}</strong><span>{compact(t.views)} views</span><span>{t.posts} posts</span><span>{t.rate.toFixed(1)}% engagement</span><Icon name="outward" size={17} /></RasterButton>; })}</div><div className="ds-integrations"><div><h3>Go beyond the post</h3><p>Explore the website and paid-media reporting available in the full product.</p></div>{['Google Analytics', 'TikTok Ads', 'Meta Ads'].map(service => <RasterButton key={service} onClick={() => setDialog(`integration:${service}`)}>{service}<Icon name="outward" size={16} /></RasterButton>)}</div></section></>}
      {state.tab === 'team' && <section className="ds-content-panel ds-team"><div className="ds-panel-heading"><div><h2>A shared workspace.</h2><p>Manage who can see your campaign.</p></div><CurrentButton icon="arrow" onClick={() => setDialog('invite')}>Invite member </CurrentButton></div>{members.map((m, i) => <div className="ds-member" key={m.email}><span className="ds-avatar-initial">{m.name.split(' ').map(s => s[0]).slice(0, 2).join('')}</span><span><strong>{m.name}</strong><small>{m.email}</small></span><span className="ds-status">{m.role}</span>{i > 0 && <RasterButton className="ds-text-button" onClick={() => { setMembers(members.filter(x => x.email !== m.email)); setToast('Member removed from the demo workspace.'); }}>Remove</RasterButton>}</div>)}<p className="ds-panel-note">Local demo only. Invitations are not sent and no real permissions are changed.</p></section>}
      </div>
    </main>
    {selected.length > 0 && state.tab === 'posts' && <div className="ds-selection-bar" role="region" aria-label="Selected posts"><strong>{selected.length} selected</strong><RasterButton onClick={() => exportData(selectedRows)}><Icon name="download" size={16} />Export selected</RasterButton><RasterButton onClick={() => { navigator.clipboard?.writeText(selectedRows.map(p => `${location.origin}/dashboard?post=${p.id}`).join('\n')).then(() => setToast('Demo post links copied.')).catch(() => setToast('Clipboard unavailable. Use Export selected instead.')); }}><Icon name="copy" size={16} />Copy links</RasterButton><RasterButton onClick={() => { setFlagged([...new Set([...flagged, ...selected])]); setSelected([]); setToast('Selected posts flagged for review in the demo.'); }}><Icon name="flag" size={16} />Flag for review</RasterButton><RasterButton onClick={() => setSelected([])} aria-label="Clear selection"><Icon name="close" /></RasterButton></div>}
    {toast && <div className="ds-toast" role="status"><span><Icon name="check" size={16} /></span>{toast}<RasterButton aria-label="Dismiss notification" onClick={() => setToast('')}><Icon name="close" size={15} /></RasterButton></div>}
    {dialog && <Modal title={dialog === 'post' ? selectedPost?.title ?? 'Post preview' : dialog === 'creator' ? demoCreators[selectedCreator ?? 0].name : ({ export: 'Export campaign data', help: 'A little help, right here.', about: 'A workspace made for review.', metrics: 'The numbers, explained.', profile: 'Your profile', settings: 'Make yourself at home.', message: 'Message your account manager', invite: 'Invite your team', brief: 'Autumn launch · Creative brief' }[dialog] ?? dialog.replace('integration:', 'Explore '))} onClose={() => setDialog(null)} className={dialog === 'post' ? 'ds-post-dialog' : ''}>
      {dialog === 'post' && selectedPost && <PostDetail key={selectedPost.id} post={selectedPost} flagged={flagged.includes(selectedPost.id)} onFlag={() => { const p = selectedPost.id; setFlagged(flagged.includes(p) ? flagged.filter(id => id !== p) : [...flagged, p]); }} />}
      {dialog === 'creator' && selectedCreator !== null && <><div className="ds-creator-detail"><img src={demoCreators[selectedCreator].poster} alt="" /><div><h3>{demoCreators[selectedCreator].handle}</h3><p>{demoCreators[selectedCreator].country} · {demoCreators[selectedCreator].status}</p><p>{totals(periodPosts.filter(p => p.creator === selectedCreator)).posts} posts in this period</p></div></div><div className="ds-dialog-clips">{periodPosts.filter(p => p.creator === selectedCreator).slice(0, 6).map(p => <RasterButton key={p.id} onClick={() => viewPost(p)}><img src={p.poster} alt={p.title} /><span>{compact(p.views)} views</span></RasterButton>)}</div><CurrentButton icon="arrow" onClick={() => { update({ tab: 'posts', query: demoCreators[selectedCreator].handle, status: 'All statuses', page: 1 }); setDialog(null); }}>View all posts </CurrentButton></>}
      {dialog === 'export' && <div className="ds-form"><div className="ds-export-summary"><Icon name="download" size={30} /><strong>{sorted.length} posts</strong><span>{campaign.name} · {state.from}–{state.to} September 2026</span></div><p>The CSV includes every filtered post, not just this page: creator, platform, date, views, likes, comments and shares.</p><p className="ds-panel-note">All values and campaign associations are illustrative.</p><CurrentButton icon="download" onAction={async () => { exportData(); }} readyLabel="Report ready">Download CSV</CurrentButton></div>}
      {['about', 'help', 'metrics', 'brief'].includes(dialog) && <div className="ds-help-content">{dialog === 'metrics' ? <><h3>One source for every number.</h3><p>Views, likes, comments and shares are summed from the posts within the selected reporting period and platform.</p><p><strong>Engagement rate</strong> = (likes + comments + shares) ÷ views × 100.</p><p><strong>Creators publishing</strong> counts distinct creators with a post in the filtered set. Daily charts show that day’s total; cumulative charts add each day within the selected range.</p></> : dialog === 'brief' ? <><h3>Everyday moments. Original voices.</h3><p>Show one useful benefit in a familiar setting. Lead with the moment your audience recognizes, then introduce the product naturally.</p><ul><li>Vertical video, 15–45 seconds.</li><li>Original footage and readable captions.</li><li>Clear sponsorship disclosure.</li><li>Use your own words; avoid scripted claims.</li></ul><p>Demonstration brief only. No posting obligations are created.</p></> : <><h3>{dialog === 'about' ? 'Real footage. Illustrative results.' : 'Everything you need to explore.'}</h3><p>This is a local design preview of the 8x brand dashboard. Campaigns, names, dates, metrics and account details are fictional. Videos come from the existing 8x Social showcase and are not attributed to these fictional campaign results.</p><p>Explore the sidebar, change the reporting range, filter by platform, preview a video, or export the matching records. Your navigation and filters stay in the URL.</p><p>Team, messages, settings and review flags are temporary demo interactions. Nothing is sent to anyone or connected to a production account.</p></>}<CurrentButton icon="arrow" onClick={() => setDialog(null)}>Back to the workspace </CurrentButton></div>}
      {dialog === 'message' && <form className="ds-form" onSubmit={e => { e.preventDefault(); setDialog(null); setToast('Demo message saved. Nothing was sent.'); }}><p>To Maya Chen · Account manager</p><label>Your message<textarea required minLength={3} placeholder="What would you like to discuss?" rows={5} /></label><small>This is a local preview. Messages are not sent.</small><CurrentButton icon="send" type="submit">Save demo message </CurrentButton></form>}
      {dialog === 'invite' && <form className="ds-form" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const email = String(data.get('email')).toLowerCase(); if (members.some(m => m.email === email)) { setToast('This person is already in the demo workspace.'); return; } setMembers([...members, { name: String(data.get('name')), email, role: 'Invited' }]); setDialog(null); setToast('Demo invitation added. No email was sent.'); }}><label>Name<input name="name" required placeholder="Jamie Chen" /></label><label>Email<input name="email" type="email" required placeholder="jamie@example.com" /></label><p className="ds-panel-note">Demo only. This does not send an invitation.</p><CurrentButton type="submit" icon="arrow">Add demo invitation </CurrentButton></form>}
      {dialog === 'profile' && <form className="ds-form" onSubmit={e => { e.preventDefault(); setProfile(String(new FormData(e.currentTarget).get('name')).trim() || 'Alex Carter'); setDialog(null); setToast('Profile updated for this preview.'); }}><label>Display name<input name="name" defaultValue={profile} required maxLength={40} /></label><label>Email<input value="alex@meridian.example" readOnly /></label><CurrentButton type="submit" icon="check">Save changes </CurrentButton></form>}
      {dialog === 'settings' && <div className="ds-form"><label className="ds-setting"><span><strong>Weekly digest</strong><small>Demo preference; no emails will be sent.</small></span><input type="checkbox" role="switch" checked={emailDigest} onChange={e => setEmailDigest(e.target.checked)} /></label><label className="ds-setting"><span><strong>Reduce interface motion</strong><small>Your device’s preference is also respected.</small></span><input type="checkbox" role="switch" checked={reduced} onChange={e => setReduced(e.target.checked)} /></label><CurrentButton icon="check" onClick={() => { setDialog(null); setToast('Preferences applied for this preview.'); }}>Done </CurrentButton></div>}
      {dialog.startsWith('integration:') && <div className="ds-help-content"><span className="ds-integration-art"><Dots /></span><h3>From content to outcomes.</h3><p>The full product supports connected reporting from {dialog.split(':')[1]}. This design preview does not access your accounts or start an authorization flow.</p><p>Campaign views, post performance and creator reporting are available to explore with demo data.</p><CurrentButton icon="arrow" onClick={() => setDialog(null)}>Back to analytics </CurrentButton></div>}
    </Modal>}
  </div>;
}

function PostCard({ post, onClick }: { post: DemoPost; onClick: () => void }) {
  return <RasterButton className="ds-post-card" onClick={onClick} aria-label={`Play ${post.title} by ${demoCreators[post.creator].handle}`}><span className="ds-post-image"><img src={post.poster} alt="" loading="lazy" width="240" height="180" /><span className="ds-post-platform"><PlatformMark name={post.platform} /></span><span className="ds-post-play"><Icon name="play" size={17} /></span><span className="ds-post-open">Watch post <Icon name="outward" size={13} /></span></span><span className="ds-post-handle">{demoCreators[post.creator].handle}</span><span className="ds-post-views"><strong>{compact(post.views)}</strong><span>views</span></span></RasterButton>;
}
function Empty({ onReset }: { onReset: () => void }) { return <div className="ds-empty"><Dots /><h3>No matches this time.</h3><p>Try a different search, status or reporting period.</p><CurrentButton icon="refresh" onClick={onReset}>Reset filters </CurrentButton></div>; }
function DatePicker({ from, to, onApply }: { from: number; to: number; onApply: (from: number, to: number) => void }) {
  const [start, setStart] = useState(from), [end, setEnd] = useState(to), [pickingEnd, setPickingEnd] = useState(false);
  return <div className="ds-calendar-picker"><header><strong>September 2026</strong><span>Reporting period</span></header><div className="ds-weekdays">{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((d, i) => <span key={i}>{d}</span>)}</div><div className="ds-date-grid"><span />{Array.from({ length: 30 }, (_, i) => i + 1).map(day => <RasterButton key={day} disabled={day > 24} data-selected={day >= start && day <= end} data-edge={day === start || day === end} aria-label={`September ${day}`} aria-pressed={day >= start && day <= end} onClick={() => { if (!pickingEnd) { setStart(day); setEnd(day); setPickingEnd(true); } else { setStart(Math.min(start, day)); setEnd(Math.max(start, day)); setPickingEnd(false); } }}>{day}</RasterButton>)}</div><p>{pickingEnd ? 'Choose the end date.' : `${start}–${end} September selected`}</p><CurrentButton icon="check" onClick={() => onApply(start, end)}>Apply dates </CurrentButton></div>;
}
function Calendar({ posts, onDay }: { posts: DemoPost[]; onDay: (day: number) => void }) {
  return <section className="ds-content-panel ds-calendar-view"><div className="ds-panel-heading"><div><h2>Publishing, day by day.</h2><p>September 2026 · Select a day to explore its posts.</p></div><span className="ds-status">{posts.length} posts this period</span></div><div className="ds-weekdays">{['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map(d => <span key={d}>{d}</span>)}</div><div className="ds-publishing-grid"><span />{Array.from({ length: 30 }, (_, i) => i + 1).map(day => { const rows = posts.filter(p => p.day === day); return <RasterButton key={day} disabled={day > 24} onClick={() => onDay(day)} data-today={day === 24}><strong>{day}</strong>{day > 24 ? <small>Upcoming</small> : <><span className="ds-day-dots">{rows.slice(0, 18).map(p => <i key={p.id} />)}</span><span>{rows.length} posts</span><small>{compact(totals(rows).views)} views</small></>}</RasterButton>; })}</div></section>;
}
function PostDetail({ post, flagged, onFlag }: { post: DemoPost; flagged: boolean; onFlag: () => void }) {
  const [error, setError] = useState(false), [copied, setCopied] = useState(false), [reason, setReason] = useState(false);
  return <div className="ds-post-detail"><div className="ds-player">{!error ? <video key={post.id} src={post.video} poster={post.poster} controls autoPlay muted playsInline onError={() => setError(true)} /> : <div><p>This preview could not load.</p><RasterLink href={post.source} target="_blank" rel="noreferrer">Open the original video <Icon name="outward" /></RasterLink></div>}</div><div className="ds-post-info"><PlatformMark name={post.platform} /><h3>{demoCreators[post.creator].handle}</h3><p>{post.title}</p><span className="ds-status">{post.status} · {post.day} September 2026</span><dl>{[['Views', post.views], ['Likes', post.likes], ['Comments', post.comments], ['Shares', post.shares]].map(([k, v]) => <div key={k}><dt>{k}</dt><dd>{compact(Number(v))}</dd></div>)}</dl>{post.spark && <RasterButton className="ds-secondary" onClick={() => { navigator.clipboard?.writeText(post.spark).then(() => setCopied(true)).catch(() => setCopied(false)); }}><Icon name="copy" size={16} />{copied ? 'Demo Spark code copied' : 'Copy demo Spark code'}</RasterButton>}<RasterButton className="ds-text-button" onClick={() => flagged ? onFlag() : setReason(!reason)}><Icon name="flag" size={16} />{flagged ? 'Flagged · remove flag' : 'Flag for review'}</RasterButton>{reason && !flagged && <form className="ds-flag-form" onSubmit={(e: FormEvent) => { e.preventDefault(); onFlag(); setReason(false); }}><label>Reason for review<textarea required minLength={3} placeholder="What should the team look at?" /></label><CurrentButton type="submit" icon="check">Save demo flag</CurrentButton></form>}<p className="ds-panel-note">Illustrative identity and results. Footage is from the 8x Social showcase; no real campaign association is implied.</p></div></div>;
}
